'use strict';

/**
 * mock_atharva_renderer.js
 *
 * Phase 5 — Atharva Integration Proof
 *
 * This is the mock Atharva execution layer renderer.
 * It simulates exactly what Atharva's real renderer must do:
 *
 *   1. Connect to /simulate/stream namespace
 *   2. Send stream:start with a trace_id (upstream authority)
 *   3. Consume stream:tick delta payloads
 *   4. Emit execution events per tick:
 *        - render:entity_update  (per changed entity)
 *        - render:tick_complete  (per tick)
 *   5. On stream:done → emit execution:complete
 *   6. Log everything with timestamps for proof
 *
 * Integration contract (what Atharva's real layer must implement):
 *   INBOUND  (from Rudra's sim node):
 *     stream:tick  { trace_id, tick_id, timestamp, entities[] }
 *     stream:done  { trace_id, ticks_run, status }
 *     stream:error { code, reason, trace_id }
 *
 *   OUTBOUND (Atharva emits after consuming each tick):
 *     render:entity_update  { trace_id, tick_id, entity_id, position, state }
 *     render:tick_complete  { trace_id, tick_id, entity_count, ts }
 *     execution:complete    { trace_id, ticks_consumed, status, ts }
 *
 * Run:
 *   node mock_atharva_renderer.js
 *
 * Server must be running first:
 *   node index.js
 */

const { io } = require('socket.io-client');

const SERVER_URL = 'http://localhost:3000';
const NAMESPACE  = '/simulate/stream';

// Trace ID originates HERE (upstream authority) — never generated by sim node
const TRACE_ID   = 'atharva-trace-' + Date.now();
const TICKS      = 8;

// ── Execution event log — proof of consumption ────────────────────────────────
const execution_log = [];

function logEvent(type, data) {
  const entry = { type, ...data, ts: new Date().toISOString() };
  execution_log.push(entry);
  console.log(`[ATHARVA RENDERER] ${type}`, JSON.stringify(data));
}

// ── Contract ──────────────────────────────────────────────────────────────────
const CONTRACT = {
  trace_id:     TRACE_ID,
  execution_id: 'atharva-exec-' + Date.now(),
  domain:       'maritime',
  scenario:     'patrol_route',
  ticks:        TICKS,
  entities: [
    {
      id:        'vessel_alpha',
      type:      'vessel',
      position:  [0, 0, 0],
      behaviors: ['patrol_main'],
      state:     'active'
    },
    {
      id:        'vessel_beta',
      type:      'vessel',
      position:  [15, 0, 0],
      behaviors: ['patrol_main'],
      state:     'active'
    },
    {
      id:        'marker_1',
      type:      'marker',
      position:  [7, 0, 0],
      behaviors: ['anchor_main'],
      state:     'idle'
    }
  ],
  behaviors: [
    {
      id:     'patrol_main',
      script: 'patrol',
      params: { waypoints: [[0,0,0],[8,0,0],[15,0,0]], speed: 1.5 }
    },
    {
      id:     'anchor_main',
      script: 'anchor',
      params: {}
    }
  ]
};

// ── Renderer state ────────────────────────────────────────────────────────────
let ticks_consumed    = 0;
let entity_updates    = 0;
let stream_start_ts   = null;

// ── Connect ───────────────────────────────────────────────────────────────────
console.log('\n╔══════════════════════════════════════════════════════╗');
console.log('║         MOCK ATHARVA RENDERER — PHASE 5             ║');
console.log('╚══════════════════════════════════════════════════════╝\n');
console.log(`[ATHARVA] Connecting to ${SERVER_URL}${NAMESPACE}`);
console.log(`[ATHARVA] trace_id (upstream authority): ${TRACE_ID}`);
console.log(`[ATHARVA] ticks requested: ${TICKS}\n`);

const socket = io(`${SERVER_URL}${NAMESPACE}`, {
  transports: ['websocket'],
  reconnection: false
});

socket.on('connect_error', (err) => {
  console.error(`[ATHARVA] ❌ Cannot connect: ${err.message}`);
  console.error('[ATHARVA] Start the server first: node index.js\n');
  process.exit(1);
});

socket.on('connect', () => {
  console.log(`[ATHARVA] ✓ Connected — socket.id=${socket.id}`);
  console.log(`[ATHARVA] Sending stream:start with trace_id=${TRACE_ID}\n`);

  stream_start_ts = Date.now();

  logEvent('STREAM_START_SENT', {
    trace_id:     TRACE_ID,
    execution_id: CONTRACT.execution_id,
    ticks:        TICKS
  });

  socket.emit('stream:start', { contract: CONTRACT });
});

// ── Consume delta ticks ───────────────────────────────────────────────────────
socket.on('stream:tick', (delta) => {
  ticks_consumed++;

  console.log(`\n[ATHARVA] ← stream:tick received`);
  console.log(`  trace_id : ${delta.trace_id}`);
  console.log(`  tick_id  : ${delta.tick_id}`);
  console.log(`  timestamp: ${delta.timestamp}`);
  console.log(`  entities : ${delta.entities.length} changed`);

  // Validate trace_id continuity
  if (delta.trace_id !== TRACE_ID) {
    console.error(`[ATHARVA] ❌ TRACE BREACH: expected ${TRACE_ID}, got ${delta.trace_id}`);
    process.exit(1);
  }

  // Process each changed entity — emit render:entity_update
  for (const entity of delta.entities) {
    entity_updates++;

    const render_event = {
      trace_id:  delta.trace_id,
      tick_id:   delta.tick_id,
      entity_id: entity.id,
      type:      entity.type,
      position:  entity.position,
      state:     entity.state,
      attributes: entity.attributes
    };

    logEvent('render:entity_update', render_event);
    console.log(`  → render:entity_update | ${entity.id} | pos=(${entity.position.x.toFixed(2)},${entity.position.y.toFixed(2)},${entity.position.z.toFixed(2)}) | state=${entity.state}`);
  }

  // Emit render:tick_complete
  const tick_complete = {
    trace_id:     delta.trace_id,
    tick_id:      delta.tick_id,
    entity_count: delta.entities.length,
    ts:           Date.now()
  };

  logEvent('render:tick_complete', tick_complete);
  console.log(`  → render:tick_complete | tick_id=${delta.tick_id} | ${delta.entities.length} entities processed`);
});

// ── Stream complete ───────────────────────────────────────────────────────────
socket.on('stream:done', (summary) => {
  const elapsed = Date.now() - stream_start_ts;

  console.log('\n[ATHARVA] ← stream:done received');
  console.log(JSON.stringify(summary, null, 2));

  // Emit execution:complete
  const completion = {
    trace_id:        summary.trace_id,
    execution_id:    summary.execution_id,
    ticks_consumed,
    entity_updates,
    status:          'execution_complete',
    elapsed_ms:      elapsed,
    ts:              Date.now()
  };

  logEvent('execution:complete', completion);

  // Print full execution log
  console.log('\n╔══════════════════════════════════════════════════════╗');
  console.log('║              EXECUTION EVENT LOG                    ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  for (const entry of execution_log) {
    console.log(JSON.stringify(entry));
  }

  // Print summary
  console.log('\n╔══════════════════════════════════════════════════════╗');
  console.log('║              CONVERGENCE PROOF SUMMARY              ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');
  console.log(`  trace_id        : ${TRACE_ID}`);
  console.log(`  ticks consumed  : ${ticks_consumed} / ${TICKS}`);
  console.log(`  entity updates  : ${entity_updates}`);
  console.log(`  elapsed         : ${elapsed}ms`);
  console.log(`  status          : ${summary.status}`);
  console.log(`  trace continuity: ${ticks_consumed === TICKS ? '✓ INTACT' : '✗ BROKEN'}`);
  console.log(`  stream parity   : ${summary.ticks_run === TICKS ? '✓ CONFIRMED' : '✗ MISMATCH'}`);
  console.log('');

  if (ticks_consumed === TICKS && summary.status === 'completed') {
    console.log('✓ PHASE 5 CONVERGENCE PROOF: LIVE INTEGRATION CONFIRMED\n');
  } else {
    console.log('✗ PHASE 5 CONVERGENCE PROOF: FAILED\n');
    process.exit(1);
  }

  socket.disconnect();
});

// ── Stream error ──────────────────────────────────────────────────────────────
socket.on('stream:error', (err) => {
  logEvent('STREAM_ERROR', err);
  console.error(`\n[ATHARVA] ❌ stream:error — code=${err.code} reason=${err.reason}`);
  console.error('[ATHARVA] Integration failed — stream error received\n');
  socket.disconnect();
  process.exit(1);
});
