apiVersion: v1
kind: Secret
metadata:
  name: mitra-secrets
  namespace: mitra
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://user:pass@cluster.mongodb.net/?appName=Mitra"
  API_KEY: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
  GROQ_API_KEY: ""
  OPENAI_API_KEY: ""
  GOOGLE_API_KEY: ""
  MISTRAL_API_KEY: ""
