apiVersion: v1
kind: Service
metadata:
  name: mitra-core
  namespace: mitra
  labels:
    app: mitra-core
spec:
  selector:
    app: mitra-core
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mitra-mongodb
  namespace: mitra
  labels:
    app: mitra-mongodb
spec:
  selector:
    app: mitra-mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
