package main

// tantra_emit.go — Sarathi-side TANTRA enforcement attestations.
//
// PURPOSE:
//   After the existing PDP pipeline finishes processing a Sovereign-issued
//   TANTRA decision, Sarathi emits a SECOND TANTRA payload — signed by
//   bhiv.sarathi.enforcement.prod.v1 — carrying the enforcement_binding
//   string ("CLEARED:..." / "BLOCKED:..."). This is the "Sarathi acted on
//   Sovereign's decision" attestation. Downstream observers (Bucket, Core
//   post-execution, InsightFlow) can re-verify the chain end-to-end without
//   needing to know Sarathi's internal state.
//
// SCOPING:
//   The attestation lives ALONGSIDE the existing sarathi.response/v13.0
//   surface — it does NOT replace any peer contract. It's persisted to
//   proof_logs/sarathi_enforcement_attestations.jsonl. Downstream peers
//   that want to consume it pull from that JSONL or from the new
//   `enforcement_attestation` field that the inner ingest path includes in
//   its HTTP response (see service_boundary.go change).
//
// KEYS:
//   The signing key is loaded from SARATHI_ENFORCEMENT_PRIV_PATH /
//   SARATHI_ENFORCEMENT_PUB_PATH (file paths chosen by the operator).
//   Generated by cmd_provider_keygen.go --evaluator-id bhiv.sarathi.enforcement.prod.v1.
//
//   If keys aren't configured at boot, EmitSarathiEnforcementAttestation
//   returns (nil, error) and the HTTP handler logs the failure but does NOT
//   reject the request — the existing pipeline already produced the
//   authoritative response. The attestation is supplementary, not a gate.
//
// TAG: tantra-v15.7

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// SarathiEnforcementAttestationLog is the JSONL file every emitted attestation
// appends to. One row per /sarathi/enforce success.
const SarathiEnforcementAttestationLog = "proof_logs/sarathi_enforcement_attestations.jsonl"

// SarathiEnforcementBindingPrefixCleared is the prefix Sarathi uses for the
// enforcement_binding string on ALLOW verdicts that pass every pipeline
// stage. The remainder of the string carries the human-readable reason.
const SarathiEnforcementBindingPrefixCleared = "CLEARED"

// SarathiEnforcementBindingPrefixBlocked is the prefix Sarathi uses for DENY
// verdicts or any pipeline rejection.
const SarathiEnforcementBindingPrefixBlocked = "BLOCKED"

// Operator env knobs.
const (
	EnvSarathiEnforcementPrivPath = "SARATHI_ENFORCEMENT_PRIV_PATH"
	EnvSarathiEnforcementPubPath  = "SARATHI_ENFORCEMENT_PUB_PATH"
	EnvSarathiEnforcementKeyID    = "SARATHI_ENFORCEMENT_KEY_ID"
)

// ============================================================================
// SARATHI ENFORCEMENT SIGNING KEY (lazy-loaded singleton)
// ============================================================================

var (
	sarathiEnforcementOnce      sync.Once
	sarathiEnforcementMaterial  PrivateKeyMaterial
	sarathiEnforcementKeyID     string
	sarathiEnforcementInitError error
)

// loadSarathiEnforcementSigner loads Sarathi's own enforcement signing key
// the first time it's needed. Reads through the active CryptoProvider so the
// key file format matches whichever provider is configured.
func loadSarathiEnforcementSigner() (PrivateKeyMaterial, string, error) {
	sarathiEnforcementOnce.Do(func() {
		if activeProvider == nil {
			sarathiEnforcementInitError = fmt.Errorf("tantra_emit: ActiveProvider not initialised")
			return
		}
		privPath := strings.TrimSpace(os.Getenv(EnvSarathiEnforcementPrivPath))
		if privPath == "" {
			sarathiEnforcementInitError = fmt.Errorf(
				"tantra_emit: %s not set — generate keys with `--provider-keygen --evaluator-id %s`",
				EnvSarathiEnforcementPrivPath, SarathiEnforcementEvaluatorID,
			)
			return
		}
		raw, err := os.ReadFile(privPath)
		if err != nil {
			sarathiEnforcementInitError = fmt.Errorf("tantra_emit: read %s: %w", privPath, err)
			return
		}
		priv, err := activeProvider.ParsePrivateKey(string(raw))
		if err != nil {
			sarathiEnforcementInitError = fmt.Errorf("tantra_emit: parse private key: %w", err)
			return
		}
		sarathiEnforcementMaterial = priv

		keyID := strings.TrimSpace(os.Getenv(EnvSarathiEnforcementKeyID))
		if keyID == "" {
			// Default key_id template — operator should override for rotations.
			keyID = SarathiEnforcementEvaluatorID + "#ed25519-2026-05"
			if activeProvider.Algorithm() == CryptoAlgCompositeMLDSA65Ed25519 {
				keyID = SarathiEnforcementEvaluatorID + "#composite-mldsa65-ed25519-2026-05"
			}
		}
		sarathiEnforcementKeyID = keyID
	})
	return sarathiEnforcementMaterial, sarathiEnforcementKeyID, sarathiEnforcementInitError
}

// ============================================================================
// EMIT
// ============================================================================

// EmitSarathiEnforcementAttestation builds, signs, and persists a TANTRA
// payload attributed to bhiv.sarathi.enforcement.prod.v1.
//
// Returns the signed TANTRA decision on success. The HTTP handler logs the
// returned object's decision_id in the response headers but does NOT include
// the full attestation in the inner ingest-decision response — peers consume
// it via the JSONL log or via a future polling endpoint.
//
// The function is best-effort:
//   - If signing keys aren't configured, returns (nil, error) without writing.
//   - If signing succeeds but disk persist fails, returns the in-memory result
//     and logs the persistence failure to stderr.
func EmitSarathiEnforcementAttestation(
	result *TantraVerifierResult,
	externalDec *ExternalDecision,
	now time.Time,
) (*TantraDecision, error) {
	if result == nil || result.Decision == nil {
		return nil, fmt.Errorf("tantra_emit: nil verifier result")
	}
	priv, keyID, err := loadSarathiEnforcementSigner()
	if err != nil {
		return nil, err
	}

	src := result.Decision

	// Compose the enforcement_binding string from the inner pipeline's
	// outcome. CLEARED / BLOCKED prefix mirrors the existing audit format.
	prefix := SarathiEnforcementBindingPrefixCleared
	body := fmt.Sprintf("Sarathi enforced %s for trace %s", src.Verdict, src.TraceID)
	if externalDec != nil && externalDec.Verdict == ExternalVerdictDeny {
		prefix = SarathiEnforcementBindingPrefixBlocked
	}
	enforcement := prefix + ":" + body

	material := TantraDecisionMaterial{
		SchemaVersion:   TantraSchemaV1,
		TraceID:         src.TraceID,
		InputHash:       src.InputHash,
		Verdict:         src.Verdict,
		PolicyReference: src.PolicyReference,
		EvaluatorID:     SarathiEnforcementEvaluatorID,
	}
	decisionHash := ComputeTantraDecisionHash(material)

	attest := &TantraDecision{
		SchemaVersion:      TantraSchemaV1,
		TraceID:            src.TraceID,
		InputHash:          src.InputHash,
		DecisionID:         "", // filled below from ComputeTantraDecisionID
		DecisionHash:       decisionHash,
		Verdict:            src.Verdict,
		PolicyReference:    src.PolicyReference,
		EvaluatorID:        SarathiEnforcementEvaluatorID,
		EnforcementBinding: enforcement,
		Timestamp:          now.UTC().Format(time.RFC3339Nano),
		Signature: TantraSignature{
			Alg:      string(activeProvider.Algorithm()),
			KeyID:    keyID,
			Encoding: TantraSignatureEncoding,
			Value:    "", // filled below after signing
		},
	}
	attest.DecisionID = ComputeTantraDecisionID(attest)

	// Sign the signable bytes (signature OMITTED) under the active provider.
	signable, err := CanonicalSignableBytes(attest)
	if err != nil {
		return nil, fmt.Errorf("tantra_emit: canonical signable bytes: %w", err)
	}
	sigBytes, err := activeProvider.Sign(signable, priv)
	if err != nil {
		return nil, fmt.Errorf("tantra_emit: sign: %w", err)
	}
	attest.Signature.Value = base64.RawURLEncoding.EncodeToString(sigBytes)

	// Persist (best-effort).
	if perr := persistEnforcementAttestation(attest); perr != nil {
		fmt.Fprintf(os.Stderr, "[tantra_emit] WARN persist: %v\n", perr)
	}
	return attest, nil
}

// persistEnforcementAttestation appends one JSONL row carrying the full
// signed TANTRA attestation. The file is open-on-each-write to keep the
// emission goroutine stateless; for high-QPS deployments a single-writer
// background channel can be added later — kept simple for the v15.7 cutover.
func persistEnforcementAttestation(attest *TantraDecision) error {
	dir := filepath.Dir(SarathiEnforcementAttestationLog)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("mkdir: %w", err)
		}
	}
	raw, err := json.Marshal(attest)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	raw = append(raw, '\n')
	f, err := os.OpenFile(SarathiEnforcementAttestationLog, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("open: %w", err)
	}
	defer f.Close()
	if _, err := f.Write(raw); err != nil {
		return fmt.Errorf("write: %w", err)
	}
	return nil
}
